/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package impact;
import java.util.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void testRangeNormalNumber(){
        Range rangeUnderTest = new Range(3,5);
        assertEquals("3-5", rangeUnderTest.toString());
    }

    @Test
    void testRangeWithSingleNumber(){
        Range rangeUnderTest = new Range(3,3);
        assertEquals("3", rangeUnderTest.toString());
    }

    @Test
    void testFourRanges(){
        int[] numbers = {20,21,22,44,73,74,75, 100,101};
        ArrayList<String> underTest = RangeBuilder.createRanges(numbers);
        int expected = underTest.size();
        assertEquals(4, expected);
    }
}
